// SPDX-License-Identifier: LGPL-3.0-or-later
#pragma once

#define SATELLITE_VIGEMBUS_BUNDLED_VERSION "1.22.0"
#define SATELLITE_HIDMAESTRO_SDK_VERSION "1.7.0"
#define SATELLITE_HIDMAESTRO_BUNDLED_DRIVER_VERSION "1.4.7.12"
